[package]
name = "lieutenant"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
lieutenant-macros = { path =  "macros" }

anyhow = "1.0"
thiserror = "1.0"
slab = "0.4"
smallvec = "1.4"
async-trait = "0.1"

[dev-dependencies]
criterion = "0.3"
smol = "0.1"
futures = "0.3"
thread_local = "1.0"

[[bench]]
name = "dispatcher"
harness = false

[workspace]
members = [".", "macros"]
