[package]
name = "lieutenant"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
unicase = "2.6"

[dev-dependencies]
criterion = "0.3"

[workspace]
members = [".", "macros"]

[[bench]]
name = "simple"
harness = false